# Generated by Django 2.2 on 2019-04-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_proxsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
