# Generated by Django 2.2 on 2019-04-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_estop_estopreading_lightcurtain_lightcurtainreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name2',
            field=models.CharField(default='string', max_length=15),
            preserve_default=False,
        ),
    ]
