# Generated by Django 2.2.5 on 2019-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_proximity'),
    ]

    operations = [
        migrations.CreateModel(
            name='button_readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='light_readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='switch_readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
    ]
