# Generated by Django 2.2.5 on 2019-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_button_readings_light_readings_switch_readings'),
    ]

    operations = [
        migrations.CreateModel(
            name='beacon1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='beacon2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='beacon3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
