# Generated by Django 2.2.5 on 2019-11-04 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_auto_20191103_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon1',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='beacon2',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='beacon3',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='beacon1',
            name='value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beacon2',
            name='value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beacon3',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
