# Generated by Django 2.1.12 on 2019-11-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0013_auto_20191104_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxsensor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='proxsensor',
            name='last_name',
            field=models.CharField(default='smith', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proxsensor',
            name='tagID',
            field=models.IntegerField(unique=True),
        ),
    ]
