# Generated by Django 2.1.12 on 2019-11-26 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0014_auto_20191125_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxsensor',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proxsensor',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='proxsensor',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='proxsensor',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
